"""
Does the heavy-lifting of actually executing doxygen
"""

from collections.abc import Mapping
import dataclasses
import filecmp
import json
import os
import shutil
import string
import subprocess
import sys
import tempfile
import typing


@dataclasses.dataclass(kw_only=True, frozen=True)
class DoxyBuildPaths:
    """
    Each field corresponds to a file or directory of files that are either
    dependencies of doxygen or artifacts produced by doxygen.
    """
    # The c++ source directory that doxygen docs are build from
    cpp_src_dir: os.PathLike
    # the standard doxygen file (that is committed to the repository)
    hardcoded_doxygen_file: os.PathLike
    # path to the doxygen file generated by this machinery
    generated_doxyfile: os.PathLike
    # path to the doxygen directory where the build-products are placed
    dox_build_dir: os.PathLike

    @classmethod
    def create(
        cls,
        doxybuild_build_cache_dir: os.PathLike,
        cpp_src_dir: os.PathLike,
        hardcoded_doxyfile: os.PathLike
    ):
        cur_dir = os.path.dirname(os.path.abspath(__file__))
        root_dir = os.path.abspath(os.path.join(cur_dir, "..", "..", "..", ".."))
        doxygen_dir = os.path.join(root_dir, "docs", "doxygen")

        return cls(
            cpp_src_dir=cpp_src_dir,
            hardcoded_doxygen_file=hardcoded_doxyfile,
            generated_doxyfile=os.path.join(doxybuild_build_cache_dir, "Doxyfile"),
            dox_build_dir=os.path.join(doxybuild_build_cache_dir, "html")
        )

    @property
    def build_cache_dir(self):
        return os.path.dirname(self.dox_build_dir)

    def __eq__(self, other):
        for field in dataclasses.fields(self):
            attr = field.name
            left = os.path.abspath(str(getattr(self, attr)))
            right = os.path.abspath(str(getattr(other, attr)))
            if left != right:
                return False
        return True

    def to_serialization_dict(self):
        # creates a dict (to be used for dumping JSON)
        return {field.name: str(getattr(self, field.name))
                for field in dataclasses.fields(self)}

_TEMPLATE = """
# this is a template for a Doxyfile that can be used by Sphinx
# -> the basic premise is to leave the original Doxygen file with sensible
#    defaults (so that we can build the docs without sphinx)
# -> this file will pull in those settings and selectively overwrite them

@INCLUDE = {RAW_CONF_FILE}

OUTPUT_DIRECTORY       = {OUTPUT_DIRECTORY}
INPUT                  = {INPUT}
"""
#PROJECT_NUMBER         = {DOXYGEN_VERSION_STRING}
#DOT_PATH               = {DOXYGEN_DOT_PATH}

def _write_template(f: typing.IO, template: str, mapping: Mapping[str,str]):
    # get the field names in the string
    field_name_set = set(
        quad[1] for quad in string.Formatter().parse(template) if quad[1] is not None
    )
    if len(field_name_set.symmetric_difference(mapping)) != 0:
        for name in field_name_set:
            if name not in mapping:
                raise ValueError(f"{name!r} was not provided by the mapping")
        for name in mapping:
            if name not in field_name_set:
                raise ValueError(
                    f"{name!r} was provided by the mapping, but not known to template"
                )
    else:
        f.write(template.format_map(mapping))

def write_custom_doxyfile_if_needed(build_paths: DoxyBuildPaths,
                                    extra_overrides: dict[str, str]) -> bool:
    # returns whether a new doxyfile was written (or if one was reused from
    # a prior build)

    template_mapping = {
        "RAW_CONF_FILE": os.path.abspath(build_paths.hardcoded_doxygen_file),
        "INPUT": os.path.abspath(build_paths.cpp_src_dir),
        "OUTPUT_DIRECTORY": os.path.dirname(build_paths.dox_build_dir)
    }

    with tempfile.TemporaryDirectory() as tmpdirname:
        path = os.path.join(tmpdirname, "Doxyfile")
        with open(path, "w") as f:
            _write_template(f, _TEMPLATE, template_mapping)
            for (key, value) in extra_overrides.items():
                assert key not in template_mapping # sanity check!
                f.write(f"{key} = {value}\n")
        if os.path.isfile(build_paths.generated_doxyfile):
            if filecmp.cmp(path, build_paths.generated_doxyfile, shallow=False):
                return False
            os.remove(build_paths.generated_doxyfile)
        out_dirname = os.path.dirname(build_paths.generated_doxyfile)
        if not os.path.isdir(out_dirname):
            os.makedirs(out_dirname)
        shutil.move(path, build_paths.generated_doxyfile)
    return True


def run_doxygen(build_paths: DoxyBuildPaths) -> bool:
    """
    Execute doxygen and return whether it succeeded
    """

    if os.path.exists(build_paths.dox_build_dir):
        shutil.rmtree(build_paths.dox_build_dir)

    success = False
    try:
        retcode = subprocess.call(["doxygen", build_paths.generated_doxyfile])
        if retcode == 0:
            success = True
        else:
            sys.stderr.write("doxygen terminated by signal %s" % (-retcode))
    except OSError as e:
        sys.stderr.write(f"doxygen execution failed: {e}")

    if (not success) and os.path.exists(build_paths.dox_build_dir):
        shutil.rmtree(dox_html_outdir)
    return success
