#!/bin/bash
#SBATCH --job-name=cholla_test      # Job name
#SBATCH --partition=gpuq             # queue for job submission
#SBATCH --mail-type=END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=brvillas@ucsc.edu   # Where to send mail
#SBATCH --ntasks=8                  # Number of MPI ranks
#SBATCH --nodes=1                    # Number of nodes
#SBATCH --ntasks-per-node=8         # How many tasks on each node
#SBATCH --time=00:10:00              # Time limit hrs:min:sec
#SBATCH --output=cuda_test_%j.log     # Standard output and error log

pwd; hostname; date

echo "Running program on $SLURM_JOB_NUM_NODES nodes with $SLURM_NTASKS total tasks, with each node getting $SLURM_NTASKS_PER_NODE running on cores."

module load hdf5
module load openmpi/4.0.1-cuda
module load cuda10.1/10.1.168

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/brvillas/code/grackle/lib


cd /home/brvillas/cholla

mpirun -N 1 --map-by ppr:8:node ./cholla tests/3D/Spherical_Collapse.txt

date