#!/bin/bash
# Begin LSF Directives
#BSUB -P AST149
#BSUB -W 0:10
#BSUB -nnodes 2
#BSUB -J sphere_256
#BSUB -o sphere_256.o%J
#BSUB -e sphere_256.e%J
#BSUB -alloc_flags "smt4"

module load hdf5
module load cuda

export WORK_DIR=$MEMBERWORK/ast149/sphere_explosion

cd $MEMBERWORK/ast149/cholla
date
#export OMP_NUM_THREADS=10
jsrun -n 8 -a 1 -c 7 -g 1 -r 4 -l CPU-CPU -d packed -b packed:7 ./cholla tests/3D/Spherical_Overpressure.txt > $WORK_DIR/run_output.log |sort 
