name: Build & Lint

# This runs the HIP Builds. CUDA builds can be reenabled by adding the CUDA
# container to the matrix and uncommenting the CUDA lines

on:
  pull_request:
  schedule:
    - cron: "37 07 * * 1"  # run every Monday at 07:37UTC. Crontab computed with crontab.guru
  workflow_dispatch:

jobs:
  Build:
    name: Platform=${{ matrix.container.name }} TYPE=${{ matrix.make-type }}
    # if: ${{ false }}  # If uncommented this line will disable this job
    runs-on: ubuntu-latest  # Choose OS/Runner
    container:
      image: ${{matrix.container.link}}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:  # Matrix for different make-types and platforms
        make-type: [hydro, gravity, disk, particles, cosmology, mhd, dust, cooling]
        container:
          #- {name: "CUDA", link: "docker://chollahydro/cholla:cuda_github"}
          - {name: "HIP", link: "docker://chollahydro/cholla:rocm_github"}
    env:  # Set environment variables
      CHOLLA_MAKE_TYPE: ${{ matrix.make-type }}

    # Run the job itself
    steps:
      - name: Checkout Cholla
        uses: actions/checkout@v3

      - name: Show MPI version
        run: mpirun --version

      - name: Show HDF5 config
        run: h5cc -showconfig

      - name: Show CUDA/HIP version & Compiler version(s)
        run: |
          if [[ ${{ matrix.conatainer.name }} == 'CUDA' ]]; then
            cc --version
            c++ --version
            nvcc -V
          else
            hipcc --version
            hipconfig --full
          fi

      # Is this really necessary?
      - name: Git Safe Directory
        run: |
          git --version
          git config --global --add safe.directory /__w/cholla/cholla
          git config --global --add safe.directory '*'

      - name: Cholla setup
        run: |
          make clobber
          source builds/run_tests.sh
          setupTests -c gcc
          echo "CHOLLA_ROOT           = ${CHOLLA_ROOT}"
          echo "CHOLLA_LAUNCH_COMMAND = ${CHOLLA_LAUNCH_COMMAND}"
          echo "CHOLLA_ROOT=${CHOLLA_ROOT}"                     >> $GITHUB_ENV
          echo "CHOLLA_LAUNCH_COMMAND=${CHOLLA_LAUNCH_COMMAND}" >> $GITHUB_ENV
          echo "F_OFFLOAD=${F_OFFLOAD}"                         >> $GITHUB_ENV
          echo "CHOLLA_ENVSET=${CHOLLA_ENVSET}"                 >> $GITHUB_ENV
      - name: Build Cholla
        run: |
          source builds/run_tests.sh
          buildCholla OPTIMIZE
      - name: Build Tests
        run: |
          source builds/run_tests.sh
          buildChollaTests
